---
# Snapcraft Recipe for gallery-dl
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
  ffmpeg:
    plugin: nil
    stage-packages:
      # Add the required stage packages for ffmpeg here
    - libslang2

apps:
  gallery-dl:
    adapter: full
    command-chain:
    - bin/gallery-dl-launch
    command: bin/gallery-dl
    completer: share/bash-completion/completions/gallery-dl
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

      # Satisfy FFmpeg's libpulsecommon dependency
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
